### ISSUE TITLE
Regular node does not handle reorgs correctly

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/espresso-polygon-zkevm-demo#261]
After a seemingly endless stream of docker errors, I finally got the slow tests working correctly, and [encountered a real bug](https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/actions/runs/7227287043/job/19695389361).  

* The L1 chain diverges at block 46
  `2023-12-15T22:25:26.7817200Z [22:25:26] Forking reorgme_geth_child_0_0 -> Found block 0 - 46:0x7ab on reorgme_geth_child_0_0`
* The L2 node gets a `NewBlocks` event with HotShot block 1, from L1 block 47
  ` 46043 2023-12-15T22:25:52.6723460Z zkevm-1-permissionless-node-1        | 2023-12-15T22:25:52.667Z    DEBUG   etherman/etherman.go:542        NewBlocks event detected &{FirstBlockNumber:+1 NumBlocks:+19 Raw:{Address:0x5FbDB2315678afecb367f032d93F642f64
  46043 180aa3 Topics:[0x8203a21e4f95f72e5081d5e0929b1a8c52141e123f9a14e1e74b0260fa5f52f1] Data:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 19] BlockNumber:47 TxHash:0x303
  46043 340020645eef50334fe699ceb5ac3e2b0bb1a95b0a71cc553462da2f04772 TxIndex:0 BlockHash:0x498a8dd8e7f4858fcedea97de26f2275f56979ce05ef43bcd631393add1ef8d5 Index:0 Removed:false}}    {"pid": 1, "version": ""}`
* The L2 node creates a corresponding batch with L1 block number 44, using the L1 head from the HotShot block, rather than the block containing the event
  ```
  044 2023-12-15T22:25:52.6776479Z zkevm-1-permissionless-node-1        | 2023-12-15T22:25:52.677Z    INFO    etherman/etherman.go:678        Creating batch number 1 {"pid": 1, "version": ""}
  46045 2023-12-15T22:25:52.6779111Z zkevm-1-permissionless-node-1        | 2023-12-15T22:25:52.677Z    INFO    etherman/etherman.go:721        Fetched L1 block 44, hotshot block: 1, timestamp 1702679109, transactions 0x    {"pid": 1, "version": ""}
  ```
* The L2 node goes on to process 143 batches through 59 L1 blocks
  `2023-12-15T22:27:58.8469685Z zkevm-1-permissionless-node-1        | 2023-12-15T22:27:58.844Z    INFO    etherman/etherman.go:721        Fetched L1 block 59, hotshot block: 143, timestamp 1702679270, transactions 0x  {"pid": 1, "version": ""}`
* The L1 node rejoins the network, and reorgs from block 69 to 46
  `2023-12-15T22:28:11.5711755Z [22:28:11] Joining reorgme_geth_child_0_0 -> Compare with other nodes 0 - 69:0x4a8 vs 69:0x4a8`
* The L2 node detects and handles the rerog
  ```
  65683 2023-12-15T22:28:12.5938078Z zkevm-1-permissionless-node-1        | 2023-12-15T22:28:12.576Z    DEBUG   synchronizer/synchronizer.go:481        Reverting synchronization to block: 45  {"pid": 1, "version": ""}
  65684 2023-12-15T22:28:12.5940739Z zkevm-1-permissionless-node-1        | 2023-12-15T22:28:12.581Z    INFO    ethtxmanager/ethtxmanager.go:215        processing reorg from block: 46 {"pid": 1, "version": ""}
  ```
* The L2 node gets a `NewBlocks` event starting from HotShot block 1, since all later HotShot blocks had been reorged out of the L1 state
  ```
  66011 2023-12-15T22:28:15.7771755Z zkevm-1-permissionless-node-1        | 2023-12-15T22:28:15.776Z    DEBUG   etherman/etherman.go:542        NewBlocks event detected &{FirstBlockNumber:+1 NumBlocks:+19 Raw:{Address:0x5FbDB2315678afecb367f032d93F642f64  66011 180aa3 Topics:[0x8203a21e4f95f72e5081d5e0929b1a8c52141e123f9a14e1e74b0260fa5f52f1] Data:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 19] BlockNumber:80 TxHash:0x303  66011 340020645eef50334fe699ceb5ac3e2b0bb1a95b0a71cc553462da2f04772 TxIndex:1 BlockHash:0xc21531d17eadbf97cb4e52e42ebf36d3d74677d4b02de3dd5da87d189507986f Index:2 Removed:false}}    {"pid": 1, "version": ""}
  ```
* Despite the L2 node's state having been reset, it thinks that the latest batch processed is 17, and refuses to process the new batches
  `2023-12-15T22:28:15.7823865Z zkevm-1-permissionless-node-1        | 2023-12-15T22:28:15.781Z    ERROR   etherman/etherman.go:691        received old batch 1, prev batch is &{17 45 1702679126} {"pid": 1, "version": ""}`

This happens because we store the L2 batches with an L1 block number older than the block where we received them, since we use the L1 origin from HotShot. Therefore, when we deleted all blocks older than 46 to handle the reorg, we did _not_ delete batches with L1 origin older than this, even though some of those batches were affected by the reorg -- like batch 1, which has L1 origin 44, but was received in L1 block 47.

Using the L1 origin from HotShot is correct, since we need to be consistent with the preconfirmations node, which doesn't even know about the block where we received the event from L1. However, for the non-preconfirmations node, the block where we received the event does matter -- not for computing the state, but for processing reorgs.

To fix this, we can make batches in the database reference the block they were received in, so that deleting that block will also delete the corresponding batch. But this reference can be a new column, like `ReceivedAt`, rather than the existing `BlockNumber` column, so that it does not effect execution -- it's _only_ use is to cause a deletion of that block to cascade into a deletion of the batch.

**Comment by sveitser** [comment]
Do I understand correctly that the proposed fix is to reorg out all batches derived from Ethereum Events that have been reorged out? If that's correct I would probably not use the term `ReceivedAt` but maybe something like `SettledAt`?

**Comment by jbearer** [comment]
Yes that is correct. I'm not sure `SettledAt` is good either because _technically_ the batch isn't settled until a ZK proof is posted later. We're just looking at the events where the batch is sequenced (but `SequencedAt` is also bad, because it's confusing between sequenced on HotShot and sequenced on the L1). I'll think about the name more

**Comment by sveitser** [comment]
Yeah I agree with the solution then.

Good points. Some more ideas: `PostedAt`, `EmittedAt`, `SeenAt`
